POSSIBLE_ANSWERS = {
    0: ['Nome da criança'],
    1: [
        'Entrou na sala com tranquilidade e interesse desde o primeiro dia.',
        'Chorava ou resistia ao se separar dos responsáveis, mas adaptou-se com o tempo.',
        'Entrava com autonomia, mas demonstrava certa timidez.',
        'Teve dificuldades significativas na adaptação, resistindo ao ambiente e às novas rotinas.',
        'Ainda apresenta resistência e necessita de acompanhamento constante.',
    ],
    2: [
        'Alegre e afetuosa',
        'Reservada ou tímida',
        'Energia alta e muito ativa',
        'Comunicação verbal clara',
        'Comunicação verbal com dificuldades',
        'Prefere brincar sozinha',
        'Gosta de brincar em grupo',
        'Demonstra resistência em algumas situações',
        'Outros (especifique): ___________________________',
    ],
    3: [
        'Participa ativamente, cantando, fazendo os gestos e acompanhando o ritmo.',
        'Participa com incentivo da professora, demonstrando envolvimento gradual.',
        'Observa mais do que participa, mas demonstra curiosidade.',
        'Resiste ou não participa da roda rítmica mesmo com incentivo.',
    ],
    4: [
        'Alimenta-se com autonomia, aceita a maioria dos alimentos e come concentrada.',
        'Alimenta-se com autonomia, mas tem preferências alimentares marcadas (ex: não come carnes ou legumes).',
        'Precisa de incentivo ou ajuda para se alimentar, com alguma seletividade.',
        'Apresenta resistência intensa e só aceita se houver adaptação (brinquedos, apoio direto).',
    ],
    5: [
        'Explora os espaços com segurança, interage com colegas e demonstra equilíbrio corporal.',
        'Gosta de brincar, mas inicialmente buscava ficar mais próxima do adulto.',
        'Demonstra insegurança ou pouca iniciativa para brincar.',
        'Explora com entusiasmo, mas às vezes apresenta comportamentos de risco ou esbarra nos colegas.',
        'Prefere brincadeiras específicas (ex: balanço, escorregador, pneus, casinha, etc.) ______________________',
    ],
    6: [
        'Participa com concentração, dedicação e criatividade.',
        'Precisa de incentivo, mas realiza com empenho.',
        'Apresenta resistência e só realiza após mediação ou troca.',
        'Tem dificuldade em manter-se na atividade e se dispersa facilmente.',
        'Tem preferência por algum tipo de atividade? __________________________',
    ],
    7: [
        'Fase da Célula – O desenho parte do centro e os traços saem como “raios”. Representações humanas com traços saindo de uma forma redonda (ex: cabeça com pernas e braços).',
        'Fase da Garatuja – A criança realiza rabiscos ou traços aparentemente desorganizados, com repetição de gestos. Pode dar nomes aos desenhos, mesmo sem representação reconhecível.',
        'Fase das Figuras Isoladas – O desenho apresenta elementos identificáveis como casa, árvore ou pessoas, mas sem relação entre eles. Os objetos estão soltos no espaço da folha.',
        'Fase da Cena Simples – Os elementos do desenho começam a se relacionar entre si: a figura humana ao lado da casa, o chão, o céu. Ainda são formas simples, mas já há organização espacial.',
        'Fase da Cena Completa – O desenho forma uma narrativa visual, com vários elementos interagindo. Aparecem detalhes como roupas, expressões, e cenas como festa ou brincadeira.',
    ],
    8: [
        'Escreve seu nome com o auxílio da ficha de nome.',
        'Está consolidando a escrita do nome com o auxílio da ficha.',
        'Escreve o nome de modo independente.',
    ],
    9: [
        'Reconhece as letras de seu nome.',
        'Reconhece as vogais.',
        'Reconhece todo o alfabeto.',
    ],
    10: [
        'Conta até 10.',
        'Conta até 20.',
        'Conta até 50.',
    ],
    11: [
        'De 0 a 5.',
        'De 0 a 10.',
        'De 0 a 100.',
    ],
    12: [
        'Participa com alegria e realiza diversos movimentos com desenvoltura.',
        'Inicialmente resistiu, mas passou a participar com incentivo.',
        'Participa parcialmente, com apoio individual.',
        'Ainda não participa ou se recusa frequentemente.',
    ],
    13: [
        'Sim, participa com entusiasmo e coordenação.',
        'Participa com algum incentivo, demonstrando interesse.',
        'Observa mais do que participa.',
        'Resiste ou não participa.',
    ],
    14: [
        'Demonstra concentração, interesse e respeito, participando ativamente.',
        'Participa, mas se distrai ou precisa de estímulos para manter a atenção.',
        'Tem dificuldade em manter a concentração e pode causar distrações.',
        'Resiste ao momento da leitura ou não participa.',
    ],
    15: [
        'Sim, participou com entusiasmo e envolvimento.',
        'Participou parcialmente, com incentivo.',
        'Não participou ou apresentou resistência.',
    ],
    16: [
        'Brinca criativamente com os brinquedos e incorpora personagens imaginários.',
        'Brinca, mas com limitações na criatividade ou fantasia.',
        'Prefere brincadeiras concretas, com pouca fantasia.',
        'Tem dificuldades para brincar de faz de conta.',
    ],
    17: [
        'Sim, divide espontaneamente e coopera com os colegas.',
        'Precisa de apoio da professora para negociar os brinquedos.',
        'Tem dificuldade e pode apresentar comportamentos agressivos em disputas.',
        'Prefere brincar sozinha e evita dividir.',
    ],
    18: [
        'Sim, participa da organização de forma espontânea.',
        'Precisa ser incentivada para ajudar.',
        'Resiste a guardar e pode apresentar choro ou reclamações.',
        'Não participa da organização.',
    ],
    19: [
        'Mantém atenção, participa e respeita o momento.',
        'Ouve a história, mas se distrai em alguns momentos.',
        'Precisa de estímulos para manter o foco e organização.',
        'Tem dificuldade para acompanhar e pode interromper a dinâmica.',
    ],
    20: [
        'Brinca de forma cooperativa e com entusiasmo com vários colegas.',
        'Alterna entre brincadeiras individuais e em grupo, com momentos de introspecção.',
        'Prefere brincar sozinha, com pouca interação social.',
        'Apresenta dificuldades para se relacionar e resolver conflitos.',
    ],
    21: [
        'Demonstra habilidade e segurança em movimentos corporais e manuais.',
        'Está em processo de desenvolvimento, com avanços visíveis.',
        'Apresenta dificuldades específicas, mas participa das propostas.',
        'Evita ou resiste às atividades que exigem coordenação motora.',
    ],
    22: [
        'Transmite tranquilidade e influencia positivamente o grupo.',
        'Alterna entre momentos de introspecção e envolvimento social.',
        'Demonstra muita energia, entusiasmo e afetividade intensa.',
        'Apresenta comportamentos desafiadores que exigem acolhimento constante.',
    ],
    23: [
        'Txai',
        'Renovação',
        'Caminhada da Paz',
        'Colheita',
    ],
}