QUESTIONS = {
    0: 'Nome:',
    1: 'Como foi a adaptação ?',
    2: 'Característica da criança:',
    3: 'Como ela vivencia a roda rítmica?',
    4: 'Como se alimenta na escola?',
    5: 'Como brinca nos parques? (motricidade, se envolve em conflitos? tem preferências de brincadeiras?)',
    6: 'Como realiza as atividades? (Se recusa, faz sem resistência, tem preferência por algum tipo?)',
    7: 'Qual fase do Grafismo se encontra?',
    8: 'Sabe escrever seu nome?',
    9: 'Identifica alguma letra?',
    10: 'Conta e identifica número?',
    11: 'Participa das aulas de capoeira?',
    12: 'Participa do momento de Euritimia?',
    13: 'Como participa do momento da sala de Leitura?',
    14: 'Participou do projeto Histórias Viajantes?',
    15: 'Como vivencia o momento do faz de conta na sala de aula? (brinca com os brinquedos, é capaz de dividir?)',
    16: 'Após a brincadeira, ajuda a organizar os brinquedos?',
    17: 'Como se comporta nos momentos da Roda de história?',
}

POSSIBLE_ANSWERS = {
    0: ['Nome da criança'],
    1: ['Muito bem', 'Bem', 'Regular', 'Mal', 'Muito mal'],
    2: ['Extrovertida', 'Introvertida', 'Sociável', 'Tímida', 'Outros'],
    3: ['Gosta muito', 'Gosta', 'Regular', 'Não gosta', 'Não participa'],
    4: ['Come bem', 'Come razoavelmente', 'Come pouco', 'Não come'],
    5: ['Muito bem', 'Bem', 'Regular', 'Mal', 'Muito mal'],
    6: [
        'Com facilidade',
        'Com alguma dificuldade',
        'Com muita dificuldade',
        'Não participa',
    ],
    7: [
        'Rabisco desordenado',
        'Rabisco ordenado',
        'Rabisco nomeado',
        'Pré-esquemático',
        'Esquemático',
    ],
    8: ['Sim', 'Não'],
    9: ['Sim', 'Não'],
    10: ['Sim', 'Não'],
    11: ['Sim', 'Não'],
    12: ['Sim', 'Não'],
    13: [
        'Participa com interesse dos momentos de leitura, ouvindo com atenção as histórias contadas.',
        'Demonstra curiosidade pelos livros e gosta de observar as ilustrações.',
        'Interage com os colegas comentando sobre os personagens e enredos.',
        'Reconta as histórias com suas próprias palavras, demonstrando compreensão.',
        'Participa das rodas de conversa após a leitura, expressando suas preferências.',
        'Escolhe livros de forma autônoma e manuseia com cuidado.',
        'Representa as histórias por meio de desenhos e dramatizações.',
        'Demonstra alegria e envolvimento durante os momentos na sala de leitura.',
    ],
    14: [
        'Participou ativamente do projeto, mostrando interesse pelas histórias.',
        'Participou de forma passiva, ouvindo as histórias contadas.',
        'Não participou do projeto.',
    ],
    15: [
        'Brinca com os brinquedos',
        'É capaz de dividir',
        'Brinca sozinho',
        'Não participa',
    ],
    16: ['Ajuda sempre', 'Ajuda às vezes', 'Raramente ajuda', 'Nunca ajuda'],
    17: ['Muito bem', 'Bem', 'Regular', 'Mal', 'Muito mal'],
}
